//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactus.KAnalyze {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class filthy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal filthy() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cactus.KAnalyze.filthy", typeof(filthy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 あいら
        ///あいみ 
        ///115252se
        ///11xp
        ///1234成人
        ///16dy图库
        ///16dy-图库
        ///18禁
        ///2008，小鹰号沉没
        ///222se图片
        ///2穴中出
        ///33bbb走光
        ///365qingse
        ///365青涩
        ///365青色
        ///3gpA片
        ///3P体验
        ///3P炮图 
        ///3s空间
        ///4P美眉艳图
        ///500wan专区
        ///5252se
        ///5252se.com
        ///55sss偷拍区
        ///5nxx
        ///77bbb
        ///77自拍
        ///77论坛
        ///78ai
        ///7se7dy
        ///88p干
        ///89风波
        ///8apao
        ///97ai
        ///97gan
        ///97se
        ///97sese
        ///97ss
        ///97xxoo
        ///97XXOO
        ///97干
        ///97色
        ///98bb
        ///999日本妹
        ///99bb
        ///99se
        ///99sel
        ///9nnnn
        ///a4u
        ///a4y
        ///acome
        ///adult
        ///Aiai Sakura  
        ///Aiba Rubi            
        ///Ai Fukai 
        ///Ai Hiyoshi 
        ///Aika Mayu 
        ///Aika Miura
        ///Aika Shimizu            
        ///Aika Yukino   
        ///Ai Kimijima            
        ///Aiko Iijima            
        ///Aiko Kanazawa           [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string KEY {
            get {
                return ResourceManager.GetString("KEY", resourceCulture);
            }
        }
    }
}
