//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactus.KAnalyze {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CNtoTW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CNtoTW() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cactus.KAnalyze.zh_CNtoTW", typeof(zh_CNtoTW).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 爱|愛
        ///碍|礙
        ///袄|襖
        ///肮|骯
        ///罢|罷
        ///坝|壩
        ///摆|擺襬
        ///办|辦
        ///板|闆
        ///帮|幫
        ///宝|寶
        ///报|報
        ///贝|貝
        ///备|備
        ///笔|筆
        ///币|幣
        ///毕|畢
        ///毙|斃
        ///边|邊
        ///变|變
        ///标|標
        ///表|錶
        ///别|彆
        ///宾|賓
        ///卜|蔔
        ///补|補
        ///布|佈
        ///才|纔
        ///参|參
        ///惨|慘
        ///蚕|蠶
        ///灿|燦
        ///仓|倉
        ///层|層
        ///产|產
        ///搀|攙
        ///谗|讒
        ///馋|饞
        ///缠|纏
        ///忏|懺
        ///尝|嘗
        ///偿|償
        ///厂|廠
        ///长|長
        ///床|牀
        ///车|車
        ///彻|徹
        ///陈|陳
        ///尘|塵
        ///衬|襯
        ///唇|脣
        ///称|稱
        ///惩|懲
        ///痴|癡
        ///迟|遲
        ///齿|齒
        ///冲|衝
        ///虫|蟲
        ///丑|醜
        ///筹|籌
        ///处|處
        ///触|觸
        ///出|齣
        ///础|礎
        ///刍|芻
        ///疮|瘡
        ///辞|辭
        ///从|從
        ///聪|聰
        ///丛|叢
        ///窜|竄
        ///达|達
        ///呆|獃
        ///带|帶
        ///担|擔
        ///胆|膽
        ///单|單
        ///当|當
        ///档|檔
        ///党|黨
        ///导|導
        ///灯|燈
        ///邓|鄧
        ///敌|敵
        ///籴|糴
        ///递|遞
        ///淀|澱
        ///点|點
        ///电|電
        ///垫|墊
        ///冬|鼕
        ///东|東
        ///冻|凍
        ///栋|棟
        ///动|動
        ///斗|鬥
        ///独|獨
        ///断|斷
        ///对|對
        ///队|隊
        ///吨|噸
        ///夺|奪
        ///堕 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string KEY {
            get {
                return ResourceManager.GetString("KEY", resourceCulture);
            }
        }
    }
}
